server:
  port: 18019
spring:
  application:
    name:  spring-cloud-zuul
# 网关会注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  ignored-services: '*'  #使用'*'可忽略所有微服务
  routes:
    server-provider: /server/**
