#服务端口号
server:
  port: 8888 #原来是http的8080

spring:
  application:
    name: eureka
  profiles:
    active: ${cfg.env}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
