spring:
  profiles: local #开发环境
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/dianjiu/spring-config-demo.git #配置文件所在仓库
          uri: https://gitee.com/dianjiu/spring-config-demo.git #配置文件所在仓库
          username: yourname #登录账号
          password: yourpwd #登录密码
          default-label: master #配置文件分支
          search-paths: demo-config  #配置文件所在根目录

