spring:
  profiles: test #开发环境
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dianjiu/spring-config-demo.git #配置文件所在仓库
          username: youname #登录账号
          password: youpwd #登录密码
          default-label: master #配置文件分支
          search-paths: eureka-demo-config  #配置文件所在根目录

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称